/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FalsifiedMedicineAlertReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "falsifiedMedicineAlert";
};

export type FalsifiedMedicineAlert = {
  _id: string;
  _type: "falsifiedMedicineAlert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: FalsifiedMedicineAlertReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  authority?: string;
  emergencyGuidance?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      credit?: string;
      rights?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PharmacovigilanceAlertReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pharmacovigilanceAlert";
};

export type PharmacovigilanceAlert = {
  _id: string;
  _type: "pharmacovigilanceAlert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PharmacovigilanceAlertReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  authority?: string;
  emergencyGuidance?: string;
};

export type ShortageAlertReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "shortageAlert";
};

export type ShortageAlert = {
  _id: string;
  _type: "shortageAlert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ShortageAlertReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  authority?: string;
  emergencyGuidance?: string;
};

export type AlertReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "alert";
};

export type Alert = {
  _id: string;
  _type: "alert";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: AlertReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  authority?: string;
  emergencyGuidance?: string;
};

export type TrainerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "trainer";
};

export type Trainer = {
  _id: string;
  _type: "trainer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: TrainerReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type CourseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "course";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: CourseReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  startsAt?: string;
  endsAt?: string;
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: EventReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  startsAt?: string;
  endsAt?: string;
};

export type ScientificCouncilMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "scientificCouncilMember";
};

export type ScientificCouncilMember = {
  _id: string;
  _type: "scientificCouncilMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ScientificCouncilMemberReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type GovernanceMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "governanceMember";
};

export type GovernanceMember = {
  _id: string;
  _type: "governanceMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: GovernanceMemberReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: TeamMemberReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type MediaAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mediaAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MediaAsset = {
  _id: string;
  _type: "mediaAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: MediaAssetReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  asset?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  credit?: string;
  rights?: string;
};

export type NewsletterIssueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsletterIssue";
};

export type NewsletterIssue = {
  _id: string;
  _type: "newsletterIssue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: NewsletterIssueReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type LaboratoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "laboratory";
};

export type Laboratory = {
  _id: string;
  _type: "laboratory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: LaboratoryReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type MedicinalPlantReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "medicinalPlant";
};

export type MedicinalPlant = {
  _id: string;
  _type: "medicinalPlant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: MedicinalPlantReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type ResearcherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "researcher";
};

export type Researcher = {
  _id: string;
  _type: "researcher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ResearcherReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: AuthorReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type DatasetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dataset";
};

export type Dataset = {
  _id: string;
  _type: "dataset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: DatasetReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type PolicyBriefReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "policyBrief";
};

export type PolicyBrief = {
  _id: string;
  _type: "policyBrief";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PolicyBriefReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type ReportReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "report";
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ReportReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type PublicationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publication";
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PublicationReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ArticleReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: TestimonialReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  consentValidUntil?: string;
};

export type YouthAmbassadorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "youthAmbassador";
};

export type YouthAmbassador = {
  _id: string;
  _type: "youthAmbassador";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: YouthAmbassadorReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  consentValidUntil?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type DonorCampaignReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "donorCampaign";
};

export type DonorCampaign = {
  _id: string;
  _type: "donorCampaign";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: DonorCampaignReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  paymentsEnabled?: boolean;
};

export type CallForProjectsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "callForProjects";
};

export type CallForProjects = {
  _id: string;
  _type: "callForProjects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: CallForProjectsReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  startsAt?: string;
  endsAt?: string;
};

export type PartnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "partner";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PartnerReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  agreementEvidence?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type ImpactMetricReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "impactMetric";
};

export type ImpactMetric = {
  _id: string;
  _type: "impactMetric";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ImpactMetricReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  value?: number;
  unit?: string;
  period?: string;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type CountryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "country";
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: LocationReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  coordinates?: Geopoint;
  country?: Array<
    {
      _key: string;
    } & CountryReference
  >;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Country = {
  _id: string;
  _type: "country";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: CountryReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  isoCode?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ProgramReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "program";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ProjectReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  programs?: Array<
    {
      _key: string;
    } & ProgramReference
  >;
  countries?: Array<
    {
      _key: string;
    } & CountryReference
  >;
  metrics?: Array<
    {
      _key: string;
    } & ImpactMetricReference
  >;
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: ProgramReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  countries?: Array<
    {
      _key: string;
    } & CountryReference
  >;
  partners?: Array<
    {
      _key: string;
    } & PartnerReference
  >;
};

export type PillarReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pillar";
};

export type Pillar = {
  _id: string;
  _type: "pillar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PillarReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: PageReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "fr" | "en";
  translationOf?: NavigationReference;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: PortableText;
  editorialStatus?: "draft" | "inReview" | "approved" | "archived";
  verificationStatus?: "draft" | "verified" | "archived";
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  verifiedAt?: string;
  seoDescription?: string;
  items?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legalName?: string;
  contactEmail?: string;
  montrealEnabled?: boolean;
  institutionalBar?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Source = {
  _type: "source";
  title?: string;
  publisher?: string;
  url?: string;
  publishedAt?: string;
  accessedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | FalsifiedMedicineAlertReference
  | FalsifiedMedicineAlert
  | SanityImageAssetReference
  | PortableText
  | Slug
  | PharmacovigilanceAlertReference
  | PharmacovigilanceAlert
  | ShortageAlertReference
  | ShortageAlert
  | AlertReference
  | Alert
  | TrainerReference
  | Trainer
  | CourseReference
  | Course
  | EventReference
  | Event
  | ScientificCouncilMemberReference
  | ScientificCouncilMember
  | GovernanceMemberReference
  | GovernanceMember
  | TeamMemberReference
  | TeamMember
  | MediaAssetReference
  | SanityFileAssetReference
  | MediaAsset
  | NewsletterIssueReference
  | NewsletterIssue
  | LaboratoryReference
  | Laboratory
  | MedicinalPlantReference
  | MedicinalPlant
  | ResearcherReference
  | Researcher
  | AuthorReference
  | Author
  | DatasetReference
  | Dataset
  | PolicyBriefReference
  | PolicyBrief
  | ReportReference
  | Report
  | PublicationReference
  | Publication
  | ArticleReference
  | Article
  | TestimonialReference
  | Testimonial
  | YouthAmbassadorReference
  | YouthAmbassador
  | SanityImageCrop
  | SanityImageHotspot
  | DonorCampaignReference
  | DonorCampaign
  | CallForProjectsReference
  | CallForProjects
  | PartnerReference
  | Partner
  | ImpactMetricReference
  | ImpactMetric
  | LocationReference
  | CountryReference
  | Location
  | Geopoint
  | Country
  | ProjectReference
  | ProgramReference
  | Project
  | Program
  | PillarReference
  | Pillar
  | Redirect
  | PageReference
  | Page
  | NavigationReference
  | Navigation
  | SiteSettings
  | Source
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "siteSettings"][0]{  montrealEnabled,  legalName,  contactEmail}
export type SettingsQueryResult = {
  montrealEnabled: boolean | null;
  legalName: string | null;
  contactEmail: string | null;
} | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: approvedSearchQuery
// Query: *[  language == $locale &&  editorialStatus == "approved" &&  (!defined(verificationStatus) || verificationStatus == "verified") &&  [title, coalesce(excerpt, ""), coalesce(summary, "")] match $search][0...20]{  "id": _id,  "locale": language,  "slug": slug.current,  title,  editorialStatus,  verificationStatus,  "sourceUrl": sources[0].url}
export type ApprovedSearchQueryResult = Array<{
  id: string;
  locale: "en" | "fr" | null;
  slug: string | null;
  title: string | null;
  editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
  verificationStatus: "archived" | "draft" | "verified" | null;
  sourceUrl: string | null;
}>;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: approvedBySlugQuery
// Query: *[  language == $locale &&  slug.current == $slug &&  editorialStatus == "approved" &&  (!defined(verificationStatus) || verificationStatus == "verified")][0]{  "id": _id,  "locale": language,  "slug": slug.current,  "kind": _type,  title,  "summary": excerpt,  body,  editorialStatus,  verificationStatus,  verifiedAt,  "sourceTitle": sources[0].title,  "sourceUrl": sources[0].url}
export type ApprovedBySlugQueryResult =
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "alert";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "article";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "author";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "callForProjects";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "country";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "course";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "dataset";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "donorCampaign";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "event";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "falsifiedMedicineAlert";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "governanceMember";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "impactMetric";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "laboratory";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "location";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "mediaAsset";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "medicinalPlant";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "navigation";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "newsletterIssue";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "page";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "partner";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "pharmacovigilanceAlert";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "pillar";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "policyBrief";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "program";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "project";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "publication";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "report";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "researcher";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "scientificCouncilMember";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "shortageAlert";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "teamMember";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "testimonial";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "trainer";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | {
      id: string;
      locale: "en" | "fr" | null;
      slug: string | null;
      kind: "youthAmbassador";
      title: string | null;
      summary: string | null;
      body: PortableText | null;
      editorialStatus: "approved" | "archived" | "draft" | "inReview" | null;
      verificationStatus: "archived" | "draft" | "verified" | null;
      verifiedAt: string | null;
      sourceTitle: string | null;
      sourceUrl: string | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  montrealEnabled,\n  legalName,\n  contactEmail\n}': SettingsQueryResult;
    '*[\n  language == $locale &&\n  editorialStatus == "approved" &&\n  (!defined(verificationStatus) || verificationStatus == "verified") &&\n  [title, coalesce(excerpt, ""), coalesce(summary, "")] match $search\n][0...20]{\n  "id": _id,\n  "locale": language,\n  "slug": slug.current,\n  title,\n  editorialStatus,\n  verificationStatus,\n  "sourceUrl": sources[0].url\n}': ApprovedSearchQueryResult;
    '*[\n  language == $locale &&\n  slug.current == $slug &&\n  editorialStatus == "approved" &&\n  (!defined(verificationStatus) || verificationStatus == "verified")\n][0]{\n  "id": _id,\n  "locale": language,\n  "slug": slug.current,\n  "kind": _type,\n  title,\n  "summary": excerpt,\n  body,\n  editorialStatus,\n  verificationStatus,\n  verifiedAt,\n  "sourceTitle": sources[0].title,\n  "sourceUrl": sources[0].url\n}': ApprovedBySlugQueryResult;
  }
}
